### ISSUE TITLE
Decode UDP data packet 

### ISSUE THREAD

**Issue by yss8166** [contiki-ng/contiki-ng#1004]
hello everyone,

I have a problem with decoding UDP data packet in contiki, I have used cooja to emulate sky-mote node and used the rpl-collect example. using the radio logger in cooja i was able to export the communication into pcap file, but i face many difficulties decoding the udp data. is there is a way to convert the hex decimal values into a plain text as shown in cooja mote output, but maybe in wire-shark or using python. 

**when i modify cooja code to print the payload i noticed that i get number like this :** 
97,-36,122,-51,-85,1,1,1,0,1,116,18,0,2,2,2,0,2,116,18,0,122,-11,0,0,0,0,0,0,0,0,0,1,17,0,99,4,0,30,2,-28,34,71,22,56,0,54,-106,-54,1,0,22,0,123,31,0,0,-3,16,-48,-22,95,0,94,-5,1,1,64,0,-28,2,2,0,65,0,-4,0,1,0,-123,0,-74,0,-1,-1,-1,-1,0,0,0,0,0,0,0,0,7,-39

**and the orginal plain text in cooja mote output is something like this:** 
30 0 62 0 514 1 1 0 22 8059 0 4349 60112 95 64350 257 64 740 2 65 252 1 133 182 65535 65535 0 0 0 0

 **and the hex from the pcap read like this :** 
003696CA 01001600 7B1F0000 FD10D0EA 5F005EFB 01014000 E4020200 4100FC00 01008500 B600FFFF FFFF0000 00000000 0000

I understand that this is related to byte conversation, but how to convert the byte data into plain text info .

 

thank you.

**Comment by yatch** [comment]
I'm not sure what you want to do. Printing values as hex decimals (`%02x`) instead of integers (`%d`) in cooja mote output could make it easier to compare the outputs and hex dumps from the pcap file.

Anyway, here is not a place to ask such a question:

> I understand that this is related to byte conversation, but how to convert the byte data into plain text info .

https://github.com/contiki-ng/contiki-ng/wiki/Where-to-report-issues,-ask-questions,-etc.%3F#github-issues

Closing this issue.
