### ISSUE TITLE
Porting contiki ng to new board

### ISSUE THREAD

**Issue by uo251410** [contiki-ng/contiki-ng#1221]
Hello

I have a STM32 STEVAL-MKSBOX1V1 sensor, and I wanted to know if I can port contiki ng to it. It has a ARM CortexM4 MCU, but I don't know if it fullfills the requisit of having a "on-chip peripherals (such as UART, SPI, I2C, DMA...)."

Thanks

**Comment by g-oikonomou** [comment]
As far as I can see this device has a STM32L4R9 microcontroller on it. This definitely falls within the class of MCU that I would call suitable for Contiki-NG.

Your problem is the radio: As far as I can see this device only has a BLE radio, not a .15.4 one. This means you won't be able to use the TSCH/6LoWPAN stack on it, not unless you make quite a lot of effort getting IPv6 over BLE for it.
