### ISSUE TITLE
Trying to figure out the error for "gmake: *** No rule to make target"

### ISSUE THREAD

**Issue by atulp201** [contiki-ng/contiki-ng#1571]
I have done the setup as per the steps mentioned in the tutorial: https://github.com/contiki-ng/contiki-ng/wiki/Platform-simplelink
I'm too trying to run the examples (hello-world & cc26x0-web-demo), for now I'm getting stuck at build step with:
"gmake: *** No rule to make target 'hello-world.elf' "

Plus the only thing I can see is a cross at project name, no cross on either files to check for the error.
Attached the screenshot for reference. 
Kindly please guide me, to get it resolved. Thank you.

![Screen Shot 2021-05-13 at 8 53 05 PM](https://user-images.githubusercontent.com/22424087/118147468-3aebec00-b42d-11eb-94a7-a9acd2054236.png)

**Comment by atiselsts** [comment]
Unfortunately the Contiki-NG build system has changed significantly since the tutorial was written. You should be able to build with the target equal to `hello-world` (without the `.elf`). If that does not work for some reason, try using the target name as the extension: `hello-world.cc26x0-cc13x0`.

**Comment by atulp201** [comment]
> hello-world.cc26x0-cc13x0

Thank you, it works without an extension and with "hello-world.cc26x0-cc13x0"
But still it's facing the issue with hex conversion.
![Screen Shot 2021-05-14 at 12 11 39 AM](https://user-images.githubusercontent.com/22424087/118171702-21f13400-b449-11eb-9c70-951d04558bc3.png)
