### ISSUE TITLE
Cannot flash or compile Hello world on nrf52840

### ISSUE THREAD

**Issue by emaddos** [contiki-ng/contiki-ng#1791]
Hello, 

I have a project with IoT devices that have chip-set nrf528420. I installed contiki in both Ubuntu 20.04 and 18.04 but I cannot compile using the IoT Device.
Did you test contiki on a device with the same chip-set and can you guide me to make it work.?

Thanks

**Comment by pjonsson** [comment]
About a month ago, I followed the instructions on the wiki (https://github.com/contiki-ng/contiki-ng/wiki/Platform-nrf52840) and things worked for me on Ubuntu 20.04.

**Comment by alexstanoev** [comment]
Could you share the output of `make TARGET=nrf52840` for hello-world?

**Comment by emaddos** [comment]
@pjonsson What is the device you were working with

**Comment by mbaddeley** [comment]
Maybe a stupid question, but you are using Contiki-NG right? not the old Contiki OS?

**Comment by emaddos** [comment]
@MBradbury Yes I am using Contiki-NG

**Comment by emaddos** [comment]
dos@dos-PC:~/contiki-ng/examples/hello-world$ make TARGET=nrf52840 hello-world.upload
nrfjprog -f nrf52  --sectorerase --program build/nrf52840/dk/hello-world.hex
ERROR: No debuggers were discovered.
NOTE: For additional output, try running again with logging enabled (--log).
NOTE: Any generated log error messages will be displayed.
make: *** [../../arch/cpu/nrf52840/Makefile.nrf52840:127: hello-world.upload] Error 41

**Comment by pjonsson** [comment]
I'm not sure what my device is called, but it's the one that uses TARGET=nrf52840 BOARD=dongle.

This is a recollection of what I had to do rather than a reaction to the error message from your make: unfortunately I don't recall if it was the nrf5340 or the nrf52840 device, but one of them required me to run the flash utility with some other parameters before "make hello-world.upload" started succeeding. That command wasn't described on the Wiki page I linked earlier.

Unless you want to wait for Alex to chime in, I would try adding "--log" to the nrfjprog invocation to get more information like the error message suggests.
