### ISSUE TITLE
Cooja platform error - JavaNativeFoundation

### ISSUE THREAD

**Issue by fdojurado** [contiki-ng/contiki-ng#2262]
I am currently running Cooja natively on a macOS host. If I try to compile the 'hello-world' example in Cooja Motes, I receive the below message:

` INFO [AWT-EventQueue-0] (MessageListUI.java:263) - ld: framework not found JavaNativeFoundation
 INFO [AWT-EventQueue-0] (MessageListUI.java:263) - clang: error: linker command failed with exit code 1 (use -v to see invocation)
 INFO [AWT-EventQueue-0] (MessageListUI.java:263) - make: *** [../../Makefile.include:578: build/cooja/hello-world.cooja] Error 1
 INFO [AWT-EventQueue-0] (MessageListUI.java:263) - Compilation process returned error code 2`

I find out that this error comes from:

https://github.com/contiki-ng/contiki-ng/blob/7ff09881cb74f7d9e00ec59837b6f3bb255a234b/arch/platform/cooja/Makefile.cooja#L45

Once I set the JAVA_FRAMEWORK variable to:

`JAVA_FRAMEWORK ?= JavaVM`

The problem goes away.  This has only been tested in macOS and Docker, not sure of the impacts on other platforms.

**Comment by pjonsson** [comment]
It's only OS X that uses `JAVA_FRAMEWORK`.

Some version of Xcode changed the name from `JavaVM` to `JavaNativeFoundation`, the version you are using is apparently old enough to not have the new name. If you update to the most recent Xcode, I believe things should work without changes for you.

The issue should go away once https://github.com/contiki-ng/cooja/pull/753 is merged, since that removes the need for the JDK when building Contiki-NG.

**Comment by fdojurado** [comment]
Yes, this is the case. I have just updated Xcode and now works fine without any change. Should this issue be closed once the mentioned PR is closed?
