### ISSUE TITLE
Cooja printout incompletely 

### ISSUE THREAD

**Issue by yoyo890121** [contiki-ng/contiki-ng#305]
Hi, I tried to used `tsch_schedule_print();` to print Orchestra scheduling table, but it printed incompletely in Cooja. 
It works well on cc2538dk, I think it is a Cooja bug.
![](https://i.imgur.com/q5wb9BN.png)

It can reproduce in [simple-node example](https://github.com/yoyo890121/contiki-ng/tree/cooja-printout-issue/examples/6tisch/simple-node) and [this setup (BR and a CoAP node)](https://github.com/yoyo890121/contiki-ng/blob/cooja-printout-issue/projects/tsch_schedule.csc)

Thanks!

**Comment by simonduq** [comment]
OK, I looked into this, I believe this is indeed on the cooja or cooja mote side, looks like printouts are buffered up to a certain point and then dropped. @nfi any clue where this can be configured?

BTW, https://github.com/contiki-ng/contiki-ng/pull/307 improves a number of things related to this PR.

**Comment by yatch** [comment]
I guess it's because of buffer size limitation... I'll take a look this evening.

**Comment by nfi** [comment]
Cooja by default has 1 kB buffer to store logs between ticks. If a Contiki node tries to print more than this before it yields back Cooja, the logged data will be truncated.

You could try to increase `MAX_LOG_LENGTH` in `arch/platform/cooja/sys/cooja-log.c` and see if this helps.

**Comment by yatch** [comment]
@yoyo890121 Thank you for providing the branch to reproduce the issue. I got the same result as reported with `rpl-tsch-cooja.csc` under `examples/6tisch/simple-node/` on your branch.

As @nfi suggested, `MAX_LOG_LENGTH` is the key. I added the following line into `project-conf.h`  of `examples/6tisch/simple-node/` and got the mote output shown below:
```c
#define MAX_LOG_LENGTH 2048
```
![mote-output](https://user-images.githubusercontent.com/1230923/36622749-90db6dae-1942-11e8-82c6-231adf8f498c.png)

You may have to do `clean` in order to make sure the change on `MAX_LOG_LENGTH` gets effective.

**Comment by yoyo890121** [comment]
OK, it works well.
Thank you!
