### ISSUE TITLE
Encoding and decoding Nested IEs in TSCH

### ISSUE THREAD

**Issue by mike-forster** [contiki-ng/contiki-ng#439]
I think there is a problem in the encoding and decoding of Nested IDs in TSCH.

In 802.15.4-2015 paragraph 7.4.4.1 shows the Sub-ID is in bits 8-14 but the code puts it into bits 8 - 15. In frame802154e-ie.c is the following -
```C
/* Create a MLME short IE 2-byte descriptor */
static void
create_mlme_short_ie_descriptor(uint8_t *buf, uint8_t sub_id, int ie_len)
{
  uint16_t ie_desc;
  /* MLME Short IE descriptor: b0-7: len, b8-14: sub id:, b15: type: 0 */
  ie_desc = (ie_len & 0xff) + ((sub_id & 0x7f) << 8);
  WRITE16(buf, ie_desc);
}
```
As you can see the sub_id is shifted left 8 bits rather than 7. If the Type is 0 and sub_id is 0x1c (TSCH Timeslot IE) then the ie_desc MSB is 0x1c whereas it should be 0x0e. 

On the decding side is -
```C
      case PARSING_MLME_SUBIE:
        /* MLME sub-IE: 2 bytes descriptor, c.f. fig 48q in IEEE 802.15.4e */
        /* type == 0 means short sub-IE, type == 1 means long sub-IE */
        if(type == 0) {
          /* Short sub-IE, c.f. fig 48r in IEEE 802.15.4e */
          len = ie_desc & 0x00ff; /* b0-b7 */
          id = (ie_desc & 0x7f00) >> 8; /* b8-b14 */
```
If I'm right the two errors cancel each other out but will create an interoperability problem.

Mike

**Comment by simonduq** [comment]
It's easy to get confused between the code and IEEE document, because when we shift left, the bits actually move right on the IEEE figures :p

Things look correct to me here. If we take your example with sub_id 0x1c, then this goes to bits 8--14, and bit 15 is 0. This means, the MSB has:
* 0x1c as bits 0--6;
* 0 as bit 7.

Which is 0x1c. Or am I missing something?

PS: this was tested for interop against several implems already -- but doesn't mean this is correct, I've seen instances where we found the same error in two independent implems.

**Comment by mike-forster** [comment]
Okay, I'm being an idiot. This issue can be closed.

**Comment by simonduq** [comment]
Hey no worries. These things are easier to get wrong than it looks.
