### ISSUE TITLE
Can I run border-router.native on RPI with multiple radios simultaneously?

### ISSUE THREAD

**Issue by Rockabilly15** [contiki-ng/contiki-ng#808]
I connected both cc2538 and cc2650 to my RaspberryPi. They both worked well when I ran sudo ./border-router.native fd00::1/64  -s /dev/ttyUSB0 and sudo ./border-router.native fd00::1/64  -s /dev/ttyACM0 separately. 

When I opened two terminal windows to run them at the same time, I got the reply that the device or resource busy. 

Why is this way? And what should I do if I want to connect the border-router with multiple radios?

**Comment by g-oikonomou** [comment]
Currently we don't support a single border router with more than one radio. You can of course run two border routers and each will create a separate network - you will need to make sure the two networks use different prefixes otherwise you are likely to run into problems.

The device or resource busy seems irrelevant. This will happen if a process tries to open a serial port that has already been opened by a different process

**Comment by 160221J** [comment]
I am trying to run two border routers (of two separate networks) in same Raspberry Pi (RPi 4). What are the prefixes that I need to modify in order to run both simultaneously? 
I have modified the PAN ID of the two slip radios that I have uploaded for both cc2650. What are the other parameters need to modify in slip radio? I also got the message 'buzy' while trying to run this.
