### ISSUE TITLE
UART sending

### ISSUE THREAD

**Issue by MartinNPN** [contiki-ng/contiki-ng#812]
Hello,

after i found some problems with longer debug outputs on cc1310 i took a look at the uart implementation.
The UART TX Code of the most platforms uses polling and waits hard for each byte. But for example nrf52832 uses a interrupt based ringbuffer (https://github.com/contiki-ng/contiki-ng/blob/98c6580e6f1249737235a07caebe68caed250606/arch/cpu/nrf52832/dev/uart0.c).
These waitings costs a lot of time which leads to some problems, is there any reason why it is done this way ?

i found #469 and #77 which are related to the uart and suppose changes, maybe if these points are fixed this could be fixed too.

**Comment by MartinNPN** [comment]
A simple solution would be using the hardware Fifo, it should be a 32 entry fifo, so it would improve the problem without much effort. 
Changing https://github.com/contiki-ng/contiki-ng/blob/98c6580e6f1249737235a07caebe68caed250606/arch/cpu/cc26xx-cc13xx/dev/cc26xx-uart.c#L309 to `RTIMER_BUSYWAIT_UNTIL(ti_lib_uart_char_put_non_blocking(UART0_BASE, c),6900);` (The delay is based on jn516x uart driver)

**Comment by g-oikonomou** [comment]
Non-blocking usage of the UART is absolutely fine in nodes that keep the UART always on, but can prove problematic in sleepy nodes: One needs to make sure the ringbuffer or h/w FIFO is emptied out first before allowing the device to deep sleep, otherwise you may lose characters and/or get junk output.

Most existing platforms therefore use the UART synchronously, as you observe: Either we wait for each byte to TX before returning, or we wait for the previous byte TX to finish before submitting a new one (assuming no h/w FIFO on the UART - not all have one). Hardware FIFOs can be used on some platforms.

Your recommendations to use non-blocking mode should be fine. Is the RTIMER busy wait meant as a method of waiting for the FIFO to have space if at first it does not?

There are of course more optimisations that one can apply, depending on what the requirement is. For example, on most (all?) platforms it should be possible to use DMA to TX bytes over the UART while the CPU is doing other tasks. Again, low-power operation needs to be considered.

In terms of your observed problems regarding long debug outputs, I am not aware of any. By all means report bugs if you find any.
