### ISSUE TITLE
Can't build specific .o or .elf

### ISSUE THREAD

**Issue by simonduq** [contiki-ng/contiki-ng#856]
Looks like we're no longer able to build specific .o .elf as make targets. For instance, in `example/hello-world`:
```bash
$ make TARGET=native build/native/obj/clock.o
make: *** No rule to make target `build/native/obj/clock.o'.  Stop.
```

**Comment by g-oikonomou** [comment]
This is caused by the fact that `OBJECTDIR` may have repeated path separators. This is because `BOARD` and `BUILD_DIR_CONFIG` may (or may not) be empty.

In this case `OBJECTDIR` is actually `build/native///obj/`. So `make build/native/obj/clock.o` fals as per the OP, but this actually works:
```bash
$ make build/native///obj/clock.o
using saved target 'native'
  CC        ../../arch/platform/native/./clock.c
```

The trivial fix is to make sure `OBJECTDIR` does not contain repeated path separators when either or both of the aforementioned variables are empty strings.

I'm flagging this as a bug to fix for the upcoming release.
